DEFAULT_HEDGE_PHRASES = [
    "cannot exclude",
    "cannot be excluded",
    "could represent",
    "may represent",
    "may reflect",
    "may be",
    "might be",
    "possible",
    "possibly",
    "suggestive of",
    "likely",
    "likely represents",
    "probable",
    "cannot rule out",
    "concerning for",
    "suspicious for",
    "compatible with",
    "consistent with but not diagnostic of",
]

CERTAIN_WORDS = {
    "definite",
    "definitive",
    "clear",
    "confirmed",
    "stable",
    "resolved",
    "normal",
    "no",
    "without",
    "negative",
}

UNCERTAIN_WORDS = {
    "possible",
    "possibly",
    "likely",
    "unlikely",
    "suggest",
    "suggests",
    "suggestive",
    "questionable",
    "probable",
    "cannot",
    "could",
    "may",
    "might",
}

CHEXPERT_LABELS = [
    "Atelectasis",
    "Cardiomegaly",
    "Consolidation",
    "Edema",
    "Enlarged Cardiomediastinum",
    "Fracture",
    "Lung Lesion",
    "Lung Opacity",
    "No Finding",
    "Pleural Effusion",
    "Pleural Other",
    "Pneumonia",
    "Pneumothorax",
    "Support Devices",
]
